"""customer table

Revision ID: 3770efa62374
Revises: 
Create Date: 2023-10-21 17:24:56.008302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3770efa62374'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('cusip', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('is_delisted', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('sic', sa.Integer(), nullable=True),
    sa.Column('sic_sector', sa.String(), nullable=True),
    sa.Column('sic_industry', sa.String(), nullable=True),
    sa.Column('fama_sector', sa.String(), nullable=True),
    sa.Column('fama_industry', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
